name = "MultitypeBranchingProcesses"
uuid = "308293ef-aee2-4ae5-b65c-832e3cc62f62"
authors = ["angus-lewis <angus.lewis@adelaide.edu.au> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
